would_you_rather = {
    "Çıplak fotoğraflarınızı Instagram takipçilerinizin mi yoksa büyükanne ve büyükbabanızın mı görmesini tercih edersiniz?",
  "Patronunuza yanlışlıkla müstehcen bir mesaj mı yoksa annenize seksi bir sesli mesaj mı göndermeyi tercih edersiniz?  ",
  "Eşinizle birlikte okula gitmeyi mi yoksa aynı yerde çalışmayı mı tercih edersiniz?     ",
  "Her zaman üstte olmayı mı yoksa her zaman altta olmayı mı tercih edersiniz?             ",
  "İşyerinizde seks yaparken yakalanmayı mı yoksa patronunuzun sizi bilerek seks yaparken izlemesini mi tercih edersiniz? ",
  "Bir polis memuru tarafından mı yoksa kayınpederiniz tarafından mı yakalanmayı tercih edersiniz?",
  "Sekste harika olup kötü bir vücut yapısına sahip olmayı mı yoksa sekste kötü olup harika bir vücut yapısına sahip olmayı mı tercih edersiniz?",
  "Seks sırasında kelepçelenmeyi mi yoksa gözlerinin bağlanmasını mı tercih edersin? ",
  "Her zaman azgın olmayı mı yoksa hiç orgazm olamamayı mı tercih edersiniz?  ",
  "Sapıkça mı yoksa romantik mi olmayı tercih edersiniz?  ",
  "Herkesin tamamen giyinik olduğu bir plajda çıplak olmayı mı yoksa çıplak bir plajda tamamen giyinik olmayı mı tercih edersiniz?",
  "Seks sırasında üstte mi yoksa altta mı olmayı tercih edersiniz?  ",
  "Düşük cinsel dürtüleri olan biriyle mi yoksa seks bağımlılığı olan biriyle mi birlikte olmayı tercih edersiniz?    ",
  "Yatağa başka birini getirmeyi mi yoksa aldatmayı mı tercih edersiniz?          ",
  "Would you rather catch someone masturbating or be caught masturbating?     ",
  "Partnerinizi aldatmayı ve yakalanmayı mı yoksa aldatılıp asla söylenmemesini mi tercih edersiniz?",
  "Tüm gün boyunca sarılmayı ama gece yan yana uyuyamamayı mı yoksa aynı yatakta uyumayı ama gündüz sarılamamayı mı tercih edersiniz?",
  "Çok çekici biriyle çıkmayı ama onlarla seks yapamamayı mı yoksa çirkin biriyle çıkmayı ama onlarla seks yapabilmeyi mi tercih edersiniz?",
  "Sana aşık biriyle çıkmayı mı yoksa senin aşık olduğun biriyle çıkmayı mı tercih edersiniz?",
  "Sizi öpmeyi reddeden biriyle mi yoksa size oral seks yapmayı reddeden biriyle mi çıkmayı tercih edersiniz?",
  "Islak tişört yarışmasına katılmayı mı yoksa birine kucak dansı yapmayı mı tercih edersiniz?",
  "Romantik şeyler yapmayı mı yoksa yeni kinky fikirler denemeyi mi tercih edersiniz?",
  "Dominant olmayı mı yoksa dominant olunmayı mı tercih edersiniz?",
  "İlk buluşmayı seksle mi yoksa tutkulu bir öpücükle mi bitirmeyi tercih edersiniz?",
  "Seks sırasında osurmayı mı yoksa öpüşürken geğirmeyi mi tercih edersiniz?",
  "Terfi almayı mı yoksa çekici iş arkadaşınızla yatmayı mı tercih edersiniz?",
  "Fıstık ezmesiyle mi yoksa akçaağaç şurubuyla mı masaj yapmayı tercih edersiniz?",
  "Bir gecelik ilişkiden “Hamileyim” ya da “Tedavi edilemez bir cinsel hastalığım var” mesajı almayı mı tercih edersiniz?",
  "Seks düşündüğünüzde yüzünüze tokat yemeyi mi yoksa seks sırasında sürekli hapşırmayı mı tercih edersiniz?",
  "Altın duş vermeyi mi yoksa almayı mı tercih edersiniz?",
  "Denizde çıplak yüzmeyi mi yoksa çıplak güneşlenmeyi mi tercih edersiniz?",
  "Bir takas partisine mi yoksa bir BDSM grubunun partisine mi gitmeyi tercih edersiniz?",
  "Market alışverişine iç çamaşırınızla gitmeyi mi yoksa plaja çıplak gitmeyi mi tercih edersiniz?",
  "Bir dolap dolusu seks oyuncağı mı yoksa bir dolap dolusu kinky kıyafet mi tercih edersiniz?",
  "Tam zamanlı bir partner mi yoksa ara sıra birlikte olduğunuz bir arkadaş mı tercih edersiniz?",
  "Çıplak bir fotoğrafınızın internet memesine dönüşmesini mi yoksa canlı yayında çıplak yakalanmayı mı tercih edersiniz?",
  "Aşırı sahiplenici ve yapışkan bir partner mi yoksa çok ihmalci bir partner mi tercih edersiniz?",
  "Aziz gibi bir partner mi yoksa aşırı çılgın bir partner mi tercih edersiniz?",
  "Seksi bir ses mi yoksa seksi bir vücut mu tercih edersiniz?",
  "İki yabancıyla üçlü seks mi yoksa seçtiğiniz herhangi biriyle seks mi tercih edersiniz?",
  "Tamamen yabancılarla bir grup seks mi yoksa tüm eski sevgililerinizle seks mi tercih edersiniz?",
  "Öfkeli seks mi yoksa barışma seksi mi tercih edersiniz?",
  "Hayatınızın geri kalanında her gün sıradan seks mi yoksa yılda bir kez harika seks mi tercih edersiniz?",
  "Floresan pubik kıllar mı yoksa ekstra uzun pubik kıllar mı tercih edersiniz?",
  "İyi yemek mi yoksa iyi seks mi tercih edersiniz?",
  "Yabancılarla grup seks mi yoksa tüm eski sevgililerinizle grup seks mi tercih edersiniz?",
  "Eritilmiş çikolata veya krem şanti içeren fantezi seks mi tercih edersiniz?",
  "O kadar da iyi olmayan birden fazla orgazm mı yoksa mükemmel bir orgazm mı tercih edersiniz?",
  "Tek bir partner mi yoksa birden fazla partner mi tercih edersiniz?",
  "Hayatınızın geri kalanında gerçekten maceracı seks mi yoksa romantik seks mi tercih edersiniz?",
  "Bir arabada mı yoksa bir çadırda mı seks yapmayı tercih edersiniz?",
  "Kokulu bir banyoda mı yoksa lekelerle dolu yabancı birinin yatağında mı seks yapmayı tercih edersiniz?",
  "Bir uçak tuvaletinde mi yoksa bir mağaza deneme kabininde mi seks yapmayı tercih edersiniz?",
  "Kendine zevk vermek için seks oyuncakları mı yoksa sebzeler mi tercih edersiniz?",
  "Bir yıl boyunca kıyafetlerinizle mi seks yapmayı yoksa partnerinizi bir daha asla tamamen çıplak görmemeyi mi tercih edersiniz?",
  "Aşksız seks mi yoksa sekssiz aşk mı tercih edersiniz?",
  "Buharlı duşta seks mi yoksa köpük dolu bir küvette seks mi tercih edersiniz?",
  "Karşılaştığınız her kişiyi öpmek mi yoksa partnerinizi bir daha asla öpmemek mi tercih edersiniz?",
  "Her seks yaptığınızda en popüler şarkıyı söylemek mi yoksa en popüler sanatçıyla bir kez seks yapmak mı tercih edersiniz?",
  "On dakika süren inanılmaz seks mi yoksa bir saat süren sıradan seks mi tercih edersiniz?",
  "Bir ay boyunca kontrolsüz gaz mı yoksa iş yerinde altınıza yapmak mı tercih edersiniz?",
  "Saçlarınızın çekilmesini mi yoksa sırtınızın kaşınmasını mı tercih edersiniz?",
  "Partnerinizin oduncu gibi mi yoksa şık giyimli bir yönetici gibi mi giyinmesini tercih edersiniz?",
  "Partnerinizin seksi bir kütüphaneci gibi mi yoksa egzotik bir dansçı gibi mi giyinmesini tercih edersiniz?",
  "Partnerinizin sizi bir alışveriş çılgınlığıyla mı yoksa bir uçak biletiyle mi şaşırtmasını tercih edersiniz?",
  "Seks sırasında partnerinizin kirli konuşmasını mı yoksa tamamen sessiz olmasını mı tercih edersiniz?",
  "Yetişkin içerikli arama geçmişinizin yayınlanmasını mı yoksa yetişkin bir film izlerken heyecanlanamamak mı tercih edersiniz?",
  "Karanlıkta birini öpmek mi yoksa halka açık bir yerde sevişmek mi tercih edersiniz?",
  "Birinin çenesini mi yalamak yoksa birinin baş parmağını mı emmek isterdiniz?",
  "Birinin gözbebeğini mi yalamak yoksa birinin ayak parmaklarını mı emmek isterdiniz?",
  "Playboy Malikanesi'nde mi yaşamak yoksa bir striptiz kulübünde mi yaşamak isterdiniz?",
  "Sevişme sırasında hissetme duyunuzu mu yoksa tat alma duyunuzu mu kaybetmek isterdiniz?",
  "En büyük aşkınızla on saniye mi yoksa kardeşinizin en yakın arkadaşıyla on dakika mı öpüşmek isterdiniz?",
  "Ünlü aşkınızla mı öpüşmek yoksa 5000 dolar mı almak isterdiniz?",
  "Ebeveynlerinizin yatağında mı yoksa bir yatak mağazasında mı sevişmek isterdiniz?",
  "Hayatınızın geri kalanında her gün mi mastürbasyon yapmak yoksa bir daha hiç mastürbasyon yapamamak mı isterdiniz?",
  "Sadece sabahları mı yoksa sadece geceleri mi sarılmak isterdiniz?",
  "Seks yapmak için mi ödeme yapmak yoksa seks yapmak için mi ödeme almak isterdiniz?",
  "Öğretmenin gözdesi rolünü mü oynamak yoksa doktor rolünü mü oynamak isterdiniz?",
  "Seksi bir metin mesajı mı yoksa seksi bir çıplak fotoğraf mı almak isterdiniz?",
  "Erotik bir mektup almak mı yoksa kirli bir metin mesajı göndermek mi isterdiniz?",
  "Seks sırasında eski sevgilinizin adını mı yoksa partnerinizin en iyi arkadaşının adını mı söylemek isterdiniz?",
  "İlk buluşmada mı seks yapmak yoksa altı ay beklemek mi isterdiniz?",
  "Partnerinizin kardeşiyle mi yoksa en iyi arkadaşınızın kardeşiyle mi seks yapmak isterdiniz?",
  "Bir yıl boyunca vücut kokusu mu yoksa altı ay boyunca korkunç akne mi tercih edersiniz?",
  "Ön sevişmede mi yoksa seks yaparken mi kötü olmak isterdiniz?",
  "Yutmak mı yoksa tükürmek mi?",
  "Benden mi vücut şutu almak yoksa benden mi vücut şutu almak isterdiniz?",
  "Telefonla mı yoksa metin/resim mesajlarıyla mı kirli konuşmak isterdiniz?",
  "Solunuzdaki kişiyle mi yoksa sağınızdaki kişiyle mi kirli konuşmak isterdiniz?",
  "Sıcak mum mu yoksa buz küpleriyle mi tahrik etmek isterdiniz?",
  "En iyi arkadaşınızı çıplak mı görmek yoksa en iyi arkadaşınızın sizi çıplak görmesi mi?",
  "Ebeveynlerinizi mi sevişirken görmek yoksa ebeveynlerinizin sizi sevişirken görmesi mi?",
  "Partnerinizin kendine dokunmasını izlemek mi yoksa partnerinizin sizin kendinize dokunmanızı izlemesi mi?",
  "Bir haftalığına aynı iç çamaşırını giymek mi yoksa bir gün boyunca annenizin temiz iç çamaşırını giymek mi?",
  "Kırbaçlamak mı yoksa kırbaçlanmak mı?",
  "Jöle dolu bir havuzda mı yoksa çikolatalı puding dolu bir havuzda mı çıplak güreşmek isterdiniz?",
  "Komşularınızın cinsel organlarınızı görmesi mi yoksa bir akrabanıza yanlışlıkla seksi bir mesaj göndermek mi?",
  "Soyunma dansını seven biriyle mi yoksa dudaklarıyla tahrik etmeyi bilen biriyle mi olmak isterdiniz?",
  "Bir gece kulübünden mi yoksa bir bardan mı biriyle tanışmak isterdiniz?",
  "Bir porno yıldızıyla mı çıkmak yoksa bir porno yıldızı mı olmak isterdiniz?",
  "Bir seks bağımlısıyla mı çıkmak yoksa bir bakireyle mi çıkmak isterdiniz?",
  "Yatakta önce ön sevişme ve sonra seks mi, yoksa ön sevişme olmadan seks mi tercih edersiniz?",
  "Seks sırasında pis konuşmayı mı dinlemeyi, yoksa yumuşak fısıltıları mı dinlemeyi tercih edersiniz?",
   "Kendinizi mi okşamayı, yoksa partnerinizin önünde dildo kullanmayı mı tercih edersiniz?",
   "Seks sırasında pis konuşmayı mı dinlemeyi, yoksa yumuşak fısıltıları mı dinlemeyi tercih edersiniz?",
   "Tüm vücudunuzun öpülmesini mi, yoksa dudaklarınızın sürekli öpülmesini mi tercih edersiniz?",
   "Kamuoyunda el işi yapmayı mı, yoksa kamuoyunda el işi almayı mı tercih edersiniz? ",
   "Partnerinizin oral seks yapmayı iğrenç bulmasını mı, yoksa anal sekse takıntılı olmasını mı tercih edersiniz?",
   "Sarhoşken seks mi yapmayı, yoksa uyuşturucu etkisindeyken seks mi yapmayı tercih edersiniz?",
   "Sizin ve sevgilinizin en sevdiğiniz porno yıldızlarını izlemeyi mi, yoksa onlarla birlikte mi olmayı tercih edersiniz?",
   "Sürekli sert seks mi yapmayı, yoksa sürekli nazik seks mi yapmayı tercih edersiniz?",
   "Bir seks kölesi olmayı mı, yoksa ömür boyu bakire olmayı mı tercih edersiniz?",
   "Çıplak bir fotoğraf çekimi mi yapmayı, yoksa çok seksi ve açıklayıcı bir şeyler mi giymeyi tercih edersiniz?",
   "Sadece iç çamaşırlarıyla evde dolaşmayı mı, yoksa iç çamaşırı olmadan dışarı çıkmayı mı tercih edersiniz?",
   "Çok sayıda tek gecelik ilişki mi yaşamayı, yoksa tek bir yıllık ilişki mi yaşamayı tercih edersiniz?",
   "Herkesin cinsel fantezilerini yerine getirmeyi mi, yoksa herkesin fantezilerini gerçekleştirmeyi mi tercih edersiniz? ",
   "Sexting yapmayı mı, yoksa Zoom seks yapmayı mı tercih edersiniz?",
   "Orgazm olduğunuzda hapşırmayı mı, yoksa hapşırdığınızda orgazmı mı tercih edersiniz?",
   "Bir adamın kadın kılığına girmiş olduğu bir adamla mı, yoksa bir kadının erkek kılığına girmiş olduğu bir kadınla mı seks yapmayı tercih edersiniz? ",
   "Korunarak mı yoksa korunmadan mı yapmayı tercih edersiniz? ",
   "Sinemada mı öpüşmeyi tercih edersiniz, yoksa araba arka koltuğunda mı?",
   "Yaramaz öğretmeni mi, yoksa kirli doktoru mu oynamayı tercih edersiniz?",
   "Bir igloda mı seks yapmayı tercih edersiniz, yoksa bir saunada mı? ",
   "Birinci randevuda tuvaleti tıkamayı mı, yoksa yeni bir işteki ilk gününüzde tuvaleti tıkanmayı mı tercih edersiniz? ",
   "Seks sırasında eski sevgilinizin adını mı söylemeyi, yoksa partnerinizin en iyi arkadaşının adını mı söylemeyi tercih edersiniz? ",
   "Seks için para ödemeyi mi, yoksa seks yapmak için para almayı mı tercih edersiniz? ",
},
aboutme = {
  "Senin için mükemmel bir buluşma nasıl olurdu?",
  "En çok buluşma sürecinde neye sinirleniyorsun?",
  "Hiç gittiğin en güzel buluşma hangisiydi?",
  "Hiç saçma bir buluşma deneyimi yaşadın mı?",
  "En sevdiğin koku nedir?",
  "Hiç saçma bir buluşma deneyimi yaşadın mı?",
  "Hiç aldığın en tuhaf iltifat nedir?",
  "Ruh eşine inanıyor musun?",
  "Romantik birisin mi?",
  "Bir erkek ve bir kız arkadaş olabilir mi, ama birbirine aşık olmaz mı?",
  "Seni en çok itici bulan nedir?",
  "Bir gün erkek/kız olursan ne yapardın?",
  "İlk görüşte aşka inanıyor musun?",
  "Sonsuz bir para kaynağına sahip olmayı mı, yoksa sonsuz bir aşkı mı tercih edersin?",
  "Bir erkek veya bir kızda en çekici bulduğun şey nedir?",
  "Hayali bir karakterle evlenebilseydin, kim olurdu?",
  "Daha önce kaç kız arkadaşın veya erkek arkadaşın oldu?",
  "İlk aşkın kimdi? Ne zaman oldu?",
  "Çok muhafazakâr mısın?",
  "Bir ünlüyle çıkmak istesen, kim olurdu?",
  "İlk öpüşmen kaç yaşındayken oldu?",
  "İlk öpüşmeni nasıl tanımlarsın?",
  "En sevdiğin koku nedir ve neden?",
  "Senin için en romantik buluşma fikri nedir?",
  "Çift tarihe mi gitmeyi tercih edersin, yoksa yalnız mı kalmayı?",
  "Kim senin ünlü kalp atışın?",
  "Şu anda en çok neye tutkunsun?",
  "Halka açık yerde sarılmayı mı, yoksa el ele tutmayı mı tercih edersin?",
  "Partnerinin telefonunu kurcalar mısın?",
  "Görülen en romantik film hangisiydi?",
  "Çiçek mi yoksa şeker mi almayı tercih edersin?",
  "Hiç duyduğun en romantik şarkı hangisiydi?",
  "Birinin kalbine en hızlı yolun ne olduğunu düşünüyorsun?",
  "Bir ilişkiyi bitirdikten sonra arkadaş kalmaya mı çalışırsın, yoksa onları hayatından çıkarır mısın?",
  "Güvenen biri misin?",
  "Bir partnerin duygularını incitmeyi önlemek için hiç yalan söyledin mi?",
  "Kör bir buluşmaya hiç gittin mi?",
  "Bir akşam yemeği ve film için dışarı çıkmayı mı, yoksa evde dışarıdan yemek ve televizyonda film izlemeyi mi tercih edersin?",
  "Bir lakabın var mı?",
  "Partnerin için evcil hayvan isimleri kullanmaktan hoşlanır mısın? Hangilerini?",
  "Telefonunda sadece dört uygulama tutabilirsen, hangileri olurdu?",
  "Para sorun olmasa, hangi türde bir kariyer seçerdin?",
  "Ergenken başına gelen en utanç verici şey neydi?",
  "Gizli bir yeteneğin var mı?",
  "Kötü bir gün geçirdiğinde, rahatlamak için en sevdiğin yol nedir?",
  "Çocukken büyüdüğünde ne olmak istiyordun?",
  "Kahvaltıda en sevdiğin şey nedir?",
  "Herkesin izlemesi gerektiğini düşündüğün bir film var mı?",
  "Hoşlanmaktan utanır mıydın?",
  "Suçlu zevkin hangi televizyon programı?",
  "En büyük sinir olduğun şey nedir?",
  "Kırsalda mı yoksa şehirde mi yaşamayı tercih edersin?",
  "Telefonsuz 24 saat yaşayabilir misin?",
  "Gördüğün en tuhaf rüyayı nasıl tarif edersin?",
  "En tuhaf rüyayı nasıl tarif edersin?",
  "Eğer insan vücuduna sahip olsaydın, ama bir hayvanın başı olsaydı, hangi hayvanı seçerdin?",
  "Tüm paranı mı yoksa tüm fotoğraflarını mı kaybetmeyi tercih ederdin?",
  "Yalnız yaşayabileceğin en uzun süre ne kadar olurdu?",
  "Anında bir konuda uzman olabilseydin, bu hangi konu olurdu?",
  "Günlük rutininden bir şeyi ortadan kaldırabilseydin, bu ne olurdu ve neden?",
  "Bir reality TV programında olabilseydin, hangisini seçerdin ve neden?",
},
fetish = {
  "Impact Play: İmpact play, şaplaklama, kırbaçlama, kürek çekme ve diğer türde vurmalı aktiviteleri içerir ve bunlar partnerler arasında yapılan onaylı fiziksel temasları ifade eder.",
  "Role-Playing: Büyüdüğünde hayal kurmayı bırakman gerekmez. Rol yapma, cinsel bir fanteziyi partnerinle oynamak anlamına gelir.",
  "Foot Fetish: Ayak fetişi, ayaklara masaj yapma, öpme ve koklama gibi eylemlerle ayakları tapmak isteğini içerir.",
  "Anal Sex: Anal seks yapmanız için bir anal fetişiniz olması gerekmez, ancak birçok insan özellikle popo işlerinden zevk alır.",
  "Lingerie: Renye, en yaygın fetişlerden birinin, muhtemelen şu anda çekmecende duran bir şeye odaklandığını söylüyor: iç çamaşırı.",
  "Group Sex: Grup seks, birden fazla kişiyle cinsel ilişkiye girmektir.",
  "Sensation Play: Duyusal oyunlar, farklı uyarıcıların verilmesi veya alınması üzerine geniş bir etkinlik yelpazesine atıfta bulunabilir.",
  "Orgasm Control: Orgazm kontrolüne bir örnek, altınverme adı verilen ve altınverme adı verilen alttan gelen partnerin doruğa ulaştığı ve sonra durdurulduğu - genellikle tekrarlanan bir şekilde - uygulanır.",
  "Bondage: Bağlama, bir partnerin diğerini kısıtladığı zaman ortaya çıkar.",
  "Psychological Play: En yoğun cinsel oyunlar zihinde gerçekleşir. Renye, psikolojik güç oyunları olarak BDSM'nin bir türü olarak psikolojik güç oyunlarını anlatıyor.",
  "Voyeurism and Exhibitionism: Casusluk - ya da çıplak olan veya cinsel ilişkiye giren diğerlerini izlemekten cinsel haz almak - düşündüğünüzden daha yaygındır.",
  "Cuckolding: 'Cuck' terimini sağın yalnızca bir hakaret olarak kullananlar duymuş olabilirsiniz.",
  "Erotic Humiliation: Utanmayı geri almanızı sağlar ve bundan hoşlanırsınız. Aşağılama oyunu, tipik bir fetiştir ve bu türde çok yaygındır.",
  "Spectrophilia: Bazı zamanlar insanlar için değmez olduğunda, ruhlarına hayranlık duyma fikrini içerir.",
  "Dominance and Submission: Hakimiyet ve teslimiyet, iki (veya daha fazla) kişi arasındaki onaylı erotik güç alışverişine atıfta bulunur.",
  "Autonepiophilia: Yetişkinlerin bebek gibi davrandığı bir fetiştir.",
  "Urophilia: Urophilia, idrar oyunları, altın duşlar ve sulama aktiviteleri için şık bir addır.",
  "Sadism & Masochism: Sadizm, acı verme eyleminden zevk alan bir kişi olan sadist anlamına gelir.",
  "Wax play: Mum oyunları, sevgilinizin üzerine sıcak mum dökmeyi içerir.",
  "Vorarephilia: Vorarephilia, ünlü yamyam fetiştir.",
  "Quirofilia: Quirofilia, ellerden hoşlanma fikrine atıfta bulunan bir fetiştir.",
  "Pregnancy: Evet, gebelik cinsel ilişkinin bir sonucu olabilir, ancak bazı insanları da tahrik edebilir.",
  "Tentacles: Hiçbir zaman bir porno arama kara deliğine girdiyseniz, belki anime ahtapot porno ile karşılaşmışsınızdır.",
  "Age Play: Age play'e korkmuş gibi görünmek kolaydır, ancak bu kadar yaygındır ki, farkında bile olmazsınız. Eğer bir sevgiliniz sizi bebek diye çağırdıysa, yaş oyununa katılmışsınızdır.",
  "Stranger Play: Eğer hiç yabancı biriyle buluştuysanız, belki hatta adını bilmeden bile, tebrikler, yabancılarla oyun denemişsiniz demektir.",
  "Emetofili: Uyarı: Emetofili, birinin kusmaktan cinsel olarak uyarılmasıyla ilgili bir cinsel sapkınlıktır.",
  "Klismafili: Klismafili, lavmanlardan cinsel olarak uyarılan bir durumdur.",
  "Elektrostimülasyon: Richmond'a göre, elektrostimülasyon oldukça yaygın bir fantezidir.",
  "Pasta fırlatma: Bir kızın pastanın üzerine oturması ve sonra ona gaz çıkarması.",
  "Balon hayranları: Bazı erkekler seks yaparken odalarında balonlar bulundurmayı severler.",
  "Formikofili: Böceklerle kaplanarak tahrik olun.",
  "Furiler: Hayvan kostümleri giyen insanlar.",
  "Nesne fetişizmi: Nesneleri sevme fikrini bir üst seviyeye taşımak.",
  "Ototozofili: Bir kişinin kendisini bir hayvan olarak görmekten cinsel olarak uyarılması.",
  "Macrophilia: Boyut tartışması geldiğinde, devlerin fikri onları tahrik eden makrofili hastaları için kesinlikle daha iyidir.",
  "Agalmatofili: Onlar bebek ya da heykellerle çekiliyor ve genellikle onlarla ilişki kuruyorlar.",
  "Kleptolagnia: Bir çift kelepçe takmak nispeten normal bir sapkınlıktır, ancak bu fetişe sahip insanlar gerçekten tutuklanma riski altındadır.",
  "Erotik Laktasyon: Genellikle erkeklerin kadınların meme emzirirken cinsel zevk aldığı cinsel bir sapkınlıktır.",
  "Pegging: Geleneksel olarak, pegging bir cisgender, heteroseksüel erkeğin cishet dişi partneri tarafından bir kayışlı dildo ile anal penetrasyon alması anlamına gelir.",
  "Kamusal seks: Peki, kamusal değil mi?",
  "Abasiophilia: Bu genellikle lastik, alçı veya tekerlekli sandalyeler gibi hareketlilik yardımları için bir fetiş olarak tanımlanır.",
  "Akustikofili: Belirli seslerden cinsel uyarılma.",
  "Akrotomofili: Ampute insanlara cinsel ilgi.",
  "Akucullofili: Sünnetli penislere olan fetiş.",
  "Agonofili: Sahte şiddetten zevk almak."
  "Algolagnia: Sadozimizm veya masokizm: Kendinize veya başkalarına acı verme fetişi.",
  "Alvinolagnia: Karın bölgesine cinsel çekim.",
  "Androizm: İnsan benzeri robotlar için bir fetiş veya insanların robot gibi davranması.",
  "Aksillizm: Dilinizi veya erkeklik organınızı... koltuk altının sıcak kıvrımlarına nazikçe koymaktan daha iyi bir şey var mı?",
  "Pornografi: Peki, bu bir fetiş mi yoksa bir korku mu?"


},
morally = {
   "Otobüs koltuğunda 20 dolar buluyorsunuz. Etrafta birinin düşürüp düşürmediğini sorar mısınız?",
   "Biri saldırgan bir şaka yaparsa, buna karşı çıkmak sizin sorumluluğunuz mu?",
   "Partnerinizin bir ilişkisi olduğundan şüpheleniyorsunuz ve e-posta hesabının şifresini buldunuz. E-postalarını kontrol eder misiniz?",
   "Belden aşağısı felçli zengin biri olmayı mı, yoksa fakir ama sağlıklı biri olmayı mı tercih edersiniz?",
   "Hırsızlık ahlaksızca, değil mi? Ama hırsızlık bir aç çocuğu beslemenin tek yolu olsaydı?",
   "Tatildeyken çekici biriyle tanışıp bir daha asla görmeyeceğiniz birine kendinizi daha ilginç göstermek için hikayeler uydurur musunuz?",
   "Partnerinizle birlikteyken başka birini hayal etmek doğru mu?",
   "Bir suçun görgü tanığısınız: Bir adam bir bankayı soydu, ama parayı kendisi için kullanmak yerine, çocukları besleyip giydirebilecek yoksul bir yetimhaneye bağışladı.",
   "Suçu kimin işlediğini biliyorsunuz. Bilgiyi yetkililere iletirseniz, paranın bankaya geri dönme olasılığı yüksek ve birçok çocuk ihtiyaç içinde kalacak. Ne yaparsınız?",
   "Birisi size tam olarak ne zaman öleceğinizi söyleyebilse, bunu bilmek ister miydiniz?",
   "Patronunuz, bir proje için asıl çalışmayı yapan bir meslektaşınız yerine sizi övüyor. Övgüyü kabul eder misiniz?",
   "Hiç birine ayrımcılık yaptınız mı?",
   "Mor gömlek giymesiyle tanınan bir sokak çetesi kasabanızda birkaç kişiyi soyup öldürdü. Mor gömlek giymiş bir adam kapınızı çaldı, cevap verir misiniz?",
   "‘Özgürlük’ ve ‘hürriyet’ kelimeleri, zulmedilmemek veya ayrımcılığa uğramamak anlamına mı gelir, yoksa istediğinizi yapmak anlamına mı?",
   "İşe gittiğinizde, giyinirken iki farklı ayakkabı giydiğinizi fark ederseniz, eve değişmeye gider misiniz?",
   "Bir spor etkinliğinde veya konserde daha iyi (boş) koltuklara geçmek haksızlık mı?",
   "Yeni bir partneriniz var ve opera seviyor ama siz nefret ediyorsunuz. İyi bir izlenim bırakmak için onunla operaya gider misiniz?",
   "Ne kadar kötü olursa olsun, her zaman sizden daha kötü durumda olan birinin farkında mısınız?",
   "Çocuğunuzun veya sevgilinizin hayatını bir savaşı desteklemek için feda etmeye istekli misiniz?",
   "Trende uyuyorken yaşlı bir kişi omzunuza yaslanıp uyursa, hareket eder misiniz?",
   "Yeni partnerinizin ailesiyle ilk kez tanışmaya gittiniz. Akşam yemeğinde size karaciğer servis ettiler. Karaciğerden nefret ediyorsunuz. Ne yaparsınız?",
   "Yürüyüş yaparken bir çalının içinde 50.000 dolar içeren bir çanta buluyorsunuz. Bu para şu an 10 yıl hapis yatan bir uyuşturucu satıcısı tarafından saklanmış. Parayı alır mısınız?",
   "Piyangoda büyük bir miktar para kazandınız ama hoşlanmadığınız bir akrabanız ciddi borç içinde. Kazancınızı tüm ailenizden gizler misiniz?",
   "Birine yardım ettiğinizde hiç 'Bundan bana ne fayda var?' diye düşünür müsünüz?",
   "Yeni bir televizyon düşürseniz, mağazaya geri götürüp hiç çalışmadığını söyler misiniz?",
   "Sokakta güzel ve pahalı bir bilezik bulsanız, onu saklar mısınız?",
   "Bankadan kalem almak hırsızlık sayılır mı? Peki ya bir fast-food restoranından fazladan peçete almak?",
   "Otoparkta başka bir arabaya çarptınız. Sigortanız yok. Kimse sizi görmedi. Not bırakmadan kaçar mısınız?",
   "Bir bahçe satışında veya pazarda bir şeyin belirtilen fiyatından çok daha değerli olduğunu fark ederseniz, satıcıya söylemek zorunda mısınız?",
   "Bir akşam yemeği partisine yemek servis etmek üzeresiniz ve birkaç porsiyon yemeği yere düşürdünüz. Kurtarılabilir durumda ve kimse görmedi. Yine de servis eder misiniz?",
   "Okulda, öğretmeniniz bir pencerenin kimin kırdığını bilmek istiyor. Eğer kişi itiraf etmezse, tüm sınıf cezalandırılacak. Kimin yaptığını biliyorsunuz. Söyler misiniz?",
   "Birinin yüzünde yiyecek kalıntısı olduğunu söyler misiniz?",
   "Yeni bir gömleği bir kez giyip beğenmediniz. Giyilmiş olmasına rağmen geri vermek doğru mu?",
   "10 yıldır mutlu bir evlilik sürdürüyorsunuz ama eşinizin sizinle tanışmadan önce birkaç yetişkin filminde rol aldığını keşfettiniz. Geçmişlerini size söylemedikleri için onları affedebilir misiniz?",
   "Birisi size 50 dolara aldığınız bir kolye için 500 dolar teklif etse kabul eder misiniz?",
   "Evli bir çiftle arkadaşsınız ve onlardan biri bir ilişkisi olduğunu size itiraf ediyor. Eşlerine söylemek zorunda mı hissedersiniz yoksa sessiz mi kalırsınız?",
   "88 yaşında bir adam veya kadın sizi sevgilisi olarak bir hafta sonu geçirmeye davet ediyor. Karşılığında küçük bir servet değerindeki tüm mal varlığını miras alacaksınız. Davetlerini kabul eder misiniz?",
   "Bugün öleceğinizi öğrenseniz, pişmanlıklarınız olur mu? Hayatınızın son 24 saatini geçirdiğiniz şekilde mutlu olur muydunuz?",
   "Arkadaşınızın spor arabasının anahtarlarını ödünç aldınız. Dışarıda araba sürerken hız kamerasına yakalandınız. Daha önce iki kez hız yaptığınız için ehliyetinizi kaybedebilirsiniz. Ne yaparsınız?",
   "Satın almayacağınızı bildiğiniz halde bir şeyin ücretsiz örneğini almak doğru mu?",
   "Alışveriş yaparken bir kadının çorabı çantasına attığını fark ediyorsunuz. Onu ihbar eder misiniz?",
   "Ölüm cezası olmalı mı?",
   "Caddede ciddi ihtiyaç içinde olan birine rastlıyorsunuz ve onlara çok az bir maliyetle yardım edebiliyorsunuz. Bunu yapmak ahlaki olarak zorunda mısınız?",
   "İş malzemelerini veya postayı kişisel amaçlar için kullanmak doğru mu?",
   "Toplumun zengin üyeleri, yoksul üyeler için vergi yoluyla zorunlu olarak ödeme yapmalı mı? Eğer öyleyse, ne kadar?",
   "Bir arkadaşınızın partisine davet edildiniz. Daha sonra çok daha eğlenceli bir partiye davet edildiniz. Arkadaşınızın partisine gitmemek için bir bahane uydurur musunuz?",
   "Zengin bir adam ve fakir bir adam aynı türden bir suç işliyor. Zengin adam 10.000 dolar para cezasına çarptırılırken, fakir adam bir yıl hapis cezasına çarptırılıyor. Bu adil mi?",
   "Bill Gates'in cüzdanını sokakta buluyorsunuz. İçinde 1000 dolar var. Cüzdanı ona geri gönderir misiniz?",
   "Daha lezzetli domuz eti elde etmek için domuzları kırbaçlayarak öldürmek, domuz eti tüketicilerine daha fazla zevk verecekse mazur görülebilir mi?",
   "1000 dolar hırsızlığını neden 100 dolar hırsızlığından daha fazla cezalandırıyorsunuz?",
   "Partnerinizin e-postası ortak bilgisayarınızda açık kalmış. Gelen kutusuna bakmak doğru mu? Peki ya belirli bir e-postaya bakmak?",
   "Market kasiyeri size fazla para üstü veriyor. Ona söyler misiniz?",
   "En zeki mi yoksa en çekici mi olmayı tercih edersiniz?",
   "Patronum, masraf raporunda bir yemekte olduğumu söyleyerek onu örtbas etmemi istedi. Bunu yapmalı mıyım?",
   "Bir arkadaşınızın evinizde unuttuğu bir günlüğü bulsanız, okur musunuz?",
   "Sadık bir ilişki içinde olup partnerinizle sık sık kavga etmeyi mi, yoksa sadakatsiz bir ilişki içinde olup birlikte çok mutlu olmayı mı tercih edersiniz?",
   "Bir masum insanı öldürerek on masum insanın hayatını kurtarabilirsiniz. Bunu yapmak ahlaki olarak zorunda mısınız?",
   "Organ toplamak için tamamen oluşmuş, beynsiz klonlar yetiştirmek etik midir?",
   "Aşırı derecede çekici olup çirkin biriyle mi evli olmayı, yoksa çirkin olup aşırı derecede çekici biriyle evli olmayı mı tercih edersiniz?",
   "İlk çocuğunuzu 16 yaşında mı yoksa 52 yaşında mı dünyaya getirmeyi tercih edersiniz?",
   "En iyi arkadaşınız size gururla kendi yaptığı bir resmi hediye etse ve siz resmi beğenmeseniz, yine de evinizin duvarına asar mısınız?",
   "Kör mü yoksa sağır mı olmayı tercih edersiniz?",
   "Gerçek hayatta evliyseniz, başkasıyla sanal ortamda cinsel ilişki yaşamak aldatmak sayılır mı?",
   "Her zaman doğruyu söylemek zorunda mısınız?",
},
couplesquiz = {
  "Sana ilk olarak ne çekici geldi?",
  "İlişkimiz bağlamında aşkı nasıl tanımlarsın?",
  "Bir çift olarak en sevdiğin anımız nedir?",
  "Aşk ve sevgiyi nasıl ifade edersin?",
  "İlişkimizde 'sonsuz' ne anlama geliyor?",
  "Zor zamanlarda sevgiyi ifade etmeyi nasıl başarırsın?",
  "Romantizmin ilişkimizdeki rolü nedir?",
  "Ruh eşi kavramına inanıyor musun, eğer inanıyorsan, biz ruh eşi miyiz?",
  "Aşk dilindeki farklılıkları nasıl ele alıyorsun?",
  "Birlikte yaşlanmayı nasıl hayal ediyorsun?",
  "İletişim tarzın nedir ve bir çift olarak iletişimimizi nasıl geliştirebiliriz?",
  "Yanlış anlamalar ve çatışmalarla nasıl başa çıkıyorsun?",
  "Konuşmalarımızda hangi konuların tabu veya hassas olduğunu düşünüyorsun?",
  "Teknoloji aracılığıyla (mesajlaşma, sosyal medya vb.) iletişimimiz hakkında ne düşünüyorsun?",
  "İlişkimizi tartışmak için düzenli kontrol noktaları yapmamız hakkında ne düşünüyorsun?",
  "İlişkide ihtiyaç ve beklentileri nasıl ifade etmeyi tercih edersin?",
  "Etkili iletişimin en önemli yönü senin için nedir?",
  "İlişkimizde yapıcı geri bildirim vermek ve almak hakkında ne düşünüyorsun?",
  "Dürüst iletişim için güvenli ve açık bir alan yaratmak için ne yapabiliriz?",
  "Konuşmalarımızda konuşma ve dinleme dengesini nasıl görüyorsun?",
  "İlişkimizdeki rol ve sorumlulukların bölünmesini nasıl hayal ediyorsun?",
  "Bir ilişkide finansal konularla ilgili beklentilerin nelerdir?",
  "Birbirimizin bağımsızlığı ve kişisel alanı hakkında nasıl hissediyorsun?",
  "İlişkimizde güven ve şeffaflığın rolü nedir?",
  "İlişkide karar verme sürecini nasıl yönetiyorsun?",
  "Taviz verme ile kendine sadık kalma arasındaki denge hakkında ne düşünüyorsun?",
  "Bireysel hedefler ve ortak beklentiler arasında sağlıklı bir dengeyi nasıl koruyorsun?",
  "Birbirimizin kişisel ve profesyonel gelişimini nasıl desteklersin?",
  "İlişkimizde hangi gelenekleri veya ritüelleri kurmak istersin?",
  "Farklı yaşam aşamalarını geçerken rollerimizin nasıl değişeceğini hayal ediyorsun?",
  "İlişkimizin dışındaki arkadaşlıkları korumanın önemi nedir?",
  "Birbirimizin arkadaşlarıyla vakit geçirmek hakkında nasıl hissediyorsun?",
  "Bir arkadaşta en çok hangi nitelikleri değerli buluyorsun ve bu değerleri paylaşıyor muyuz?",
  "Arkadaşlarla yaşanan çatışmaları veya anlaşmazlıkları nasıl ele alıyorsun?",
  "Bir çift olarak sosyalleşmek ile birlikte yalnız vakit geçirmek hakkında nasıl hissediyorsun?",
  "Arkadaşlar duygusal destek sağlamada hayatımızda ne rol oynar?",
  "Sosyal taahhütler ve yalnız zaman arasında denge kurmayı nasıl yönetiyorsun?",
  "Arkadaşlarla birlikte yapmaktan hoşlanacağımız aktiviteleri veya hobileri nasıl hayal ediyorsun?",
  "Bir çift olarak yeni arkadaşlar edinmek hakkında nasıl hissediyorsun?",
  "Bireysel arkadaşlıklarımızı koruma ve besleme konusunda birbirimize nasıl destek olabiliriz?",
  "Bir ilişki içinde kişisel gelişimi nasıl görüyorsun?",
  "Bireysel isteklerin ve hayallerin nelerdir?",
  "Geçmiş deneyimlerimizin ve ilişkilerimizin şimdiki ilişkimize nasıl etki edebileceğini düşünüyorsun?",
  "Kendine bakım önceliklerini nasıl belirliyorsun ve ikimizin de sağlıklı bir dengeyi koruyabilmesi için ne yapabiliriz?",
  "Stres ve sıkıntılarla nasıl başa çıkıyorsun, zor zamanlarda birbirimize nasıl destek olabiliriz?",
  "Kişisel değerler ve inançlar senin öz kimliğinde ne rol oynar?",
  "Birbirimizin bireysel gelişimini teşvik etmek ve desteklemek için ne yapabiliriz?",
  "Hangi korkuların veya güvensizliklerin var ve bunları birlikte nasıl aşabiliriz?",
  "Kişisel gelişim için dışarıdan destek (terapi veya danışmanlık gibi) aramak hakkında nasıl hissediyorsun?",
  "İlişki içinde bireysel kimliğimizi korumak için hangi adımları atabiliriz?",
  "Birlikte yapmaktan en çok hoşlandığın aktiviteler nelerdir?",
  "İlişkimizde spontane aktiviteler ile planlı aktiviteler hakkında nasıl hissediyorsun?",
  "Birlikte ne tür tatil veya seyahat deneyimlerinden hoşlanacağını hayal ediyorsun?",
  "Günlük hayatımıza kahkaha ve oyun katmak için ne yapabiliriz?",
  "Birlikte keşfetmek istediğin hobiler veya ilgi alanları nelerdir?",
  "Bir çift olarak yeni şeyler denemek hakkında nasıl hissediyorsun?",
  "Ne tür eğlencelerden hoşlanıyorsun ve bunları hayatımıza nasıl dahil edebiliriz?",
  "Birlikte dinlenme anlarını veya boş vakitleri nasıl geçiriyorsun?",
  "İlişkimizde macera ve heyecan duygusunu nasıl koruyabiliriz?",
  "Paylaşılan ilgi alanlarının bağlantımızdaki rolü nedir?",
  "İlişkimizde mahremiyeti nasıl tanımlarsın?",
  "Fiziksel yakınlık konusunda ihtiyaçların ve isteklerin nelerdir?",
  "Uzun vadeli ilişkilerde mahremiyeti korumak hakkında nasıl hissediyorsun?",
  "Duygusal yakınlığın bağlantımızdaki rolü nedir?",
  "Fiziksel yakınlığı başlatma ve ifade etme konusunda nasıl yaklaşıyorsun?",
  "Mahrem hayatımızın tatmin edici ve doyurucu kalmasını nasıl sağlayabiliriz?",
  "Fiziksel ve duygusal mahremiyet arasında sağlıklı bir dengeyi korumak hakkında ne düşünüyorsun?",
  "Mahrem hayatımızda yeni şeyler denemek ve keşfetmek hakkında nasıl hissediyorsun?",
  "Yoğun veya stresli zamanlarda duygusal yakınlık hissini nasıl yaratabiliriz?",
  "İlişkimizde mahremiyetle ilgili güvensizlikleri veya endişeleri nasıl ele alıyorsun?",
  "İlişkimizde bugüne kadar en önemli dönüm noktaları neler oldu?",
  "İlk tanıştığımızdan bu yana bir çift olarak nasıl büyüdüğümüzü hissediyorsun?",
  "Beraber hangi zorluklarla karşılaştık ve bunları nasıl aştık?",
  "İlişkimiz kişisel büyümen ve gelişimin üzerinde nasıl bir etki yarattı?",
  "Birbirimizde en sevdiğin özellikler nelerdir?",
  "Anlaşmazlıkları veya çatışmaları nasıl ele aldığımızı düşünüyorsun ve neyi geliştirebiliriz?",
  "Gelecekte bir çift olarak nasıl evrileceğimizi görüyorsun?",
  "İlişkimizin güçlü yönleri nelerdir?",
  "Bir çift olarak değişime uyum sağlama yeteneğimiz hakkında ne düşünüyorsun?",
  "İlişkimiz için ileriye dönük umutların ve hayallerin nelerdir?",
  "İlişkimizde herhangi bir ana geri dönebilseydin, hangisi olurdu ve neden?",
  "Birbirimizle iletişim kurma şeklimiz hakkında en sevdiğin şey nedir?",
  "İlişkimizin bir tema şarkısı olsaydı, ne olurdu?",
  "Sence en az değer verilen özellik nedir?",
  "Eğer istersem toplarımı yalar mısın?",
  "Öpüşürken dudaklarımı ısırır mısın?",
  "Boğazını sıktığımda hoşuna gidiyor mu?",
  "Saçını geri çektiğimde hoşuna gidiyor mu?",
  "Üzerine sert davrandığımda hoşuna gidiyor mu?",
  "Külotunu koklayabilir miyim?",
  "Oraya biraz alkol döküp yalamamı ister misin?",
  "Öpüşürken tamamen içine girmeyi sever misin?",
  "Beni hangi renk iç çamaşırıyla görmek istersin?",
  "İlk kez çıplak bir kadını nerede gördün?",
  "Hiç parkta el işi yaptın mı?",
  "Benimle ilgili en çılgın düşüncen ne oldu?",
  "Öpüşürken partnerini önden mi yoksa arkadan mı tutmayı seversin?",
  "Öpüşmeye başladığında ellerin partnerinin vücudunda ilk nereye dokunur?",
  "Hiç bir otel odasında sert bir öpüşme yaşadın mı?",
  "Asansörde hiç öpüştün mü?",
  "Penisin ne kadar uzun?",
  "Poponun yalanmasını sever misin?",
  "Şimdiye kadar kaç seks pozisyonu denedin?",
  "Yorucu bir iş gününden sonra tercih ettiğin seks pozisyonu nedir?",
  "Meme uçlarımı ısırmayı sever misin?",
  "Yüzüme boşalmak ister misin?",
  "Benimle doggy style yapmak ister misin?",
  "Yatakta iyi bir kız olmamı ister misin?",
},
sensualus = {
  "Eğer yanlışlıkla birini çıplak görürseniz, bakmaya devam mı edersiniz, yoksa başka yöne mi bakarsınız?",
  "En iyi tanışma cümleniz nedir?",
  "Bir yabancıyı öper miydiniz?",
  "Hiç doğal olarak yüzdünüz mü? Nerde?",
  "İlişkide hiç aldatma yaptınız mı?",
  "Bir ilişkide aldatıldınız mı?",
  "En sevdiğiniz buluşma etkinliği nedir?",
  "Monogamiye inanıyor musunuz?",
  "Polyamori veya açık ilişkilere inanıyor musunuz?",
  "Denemek istediğiniz fakat denemekten korktuğunuz bir şey nedir?",
  "Yalnızken en çok ne yapmayı seversiniz?",
  "Erkeklerin tüylerini temizlemesi hakkında ne düşünüyorsunuz?",
  "Halka açık gösteriler (public displays of affection) hakkında nasıl hissedersiniz?",
  "Hiç bir gecelik ilişkiniz oldu mu?",
  "Bir erkekte hangisini daha seksi bulursunuz? Kutu don mu yoksa slip mi?",
  "Bir kadında hangisini daha seksi bulursunuz? Dantel külot mu yoksa ip perde mi?",
  "Bedenin hangi kısmını en çekici buluyorsunuz?",
  "Birinin tüylerini aldırması, düzenlemesi mi yoksa doğal hali mi hoşunuza gider?",
  "Uyurken ne giyersiniz?",
  "Romantik mi, yoksa çılgın mı olan bir sevgiliye sahip olmayı mı tercih edersiniz?",
  "Hiç bir sevgiliye yanlış isimle seslendiniz mi?",
  "Kendinizin kışkırtıcı fotoğraflarını çektiniz mi?",
  "Bir birliktelik mi, yoksa bir ilişki mi tercih edersiniz?",
  "Şu an hangi renk iç çamaşırı giyiyorsunuz?",
  "Hangi tip iç çamaşırı giyiyorsunuz?",
  "Sırt masajı vermek mi, almak mı hoşunuza gider?",
  "Bir arkadaşınızla bir birliktelik yaşadınız mı?",
  "Hiç bir nudist plaja gittiniz mi?",
  "En unutulmaz öpücüğünü kiminle paylaştın?",
  "Mastürbasyon yaparken birinin seni izlemesini ister miydin?",
  "En az takdir edilen cinsel pozisyon hangisi?",
  "Bakire misin?",
  "Öpüşürken dilini kullanmayı sever misin?",
  "Partnerinin vücudundan yalamak için en iyi şey nedir?",
  "Hiç kimseyle pis gerçek oyunları oynadın mı?",
  "Ağzınıza aldırmaktan hoşlanır mısınız?",
  "En son ne zaman el ile tatmin ettiniz?",
  "Halka açık yerlerde öpüşmeyi sever misiniz?",
  "En çok neyden tahrik olursunuz?",
  "En sevdiğiniz iç çamaşırı türü nedir?",
  "En son ne zaman öpüştünüz?",
  "Seks yapmak için tercih ettiğiniz yer neresidir?",
  "Hiç prezervatif yırttınız mı?",
  "Yatak odasında cinsel konuşmayı seviyor musunuz?",
  "En sevdiğiniz öpüşme noktanız neresidir?",
  "Öpüşmeye başladığınızda ilk olarak nereye dokunursunuz?",
  "Oral seks yapmayı sever misiniz?",
  "Halka açık bir yerde porno izlediniz mi?",
  "Ne sıklıkla kendinizi tatmin edersiniz?",
  "Şu anda azgın hissediyor musunuz?",
  "En son ne zaman bir ağız işi aldın?",
  "24 saat içinde seks yaptığınız en fazla sayı kaçtır?",
  "Seks sohbetinde kullandığınız en iyi emojiler hangileridir?",
  "En vahşi cinsel arzunuz nedir?",
  "Hiç tamamen yabancı birinden bir ağız işi aldınız mı?",
  "Bu gruptan herhangi biriyle arkadaşlarla faydalar ilişkisi olmak ister misiniz?",
  "Yaptığınız en zor seks pozisyonu hangisi?",
  "İnsanların seks yaparken sizi izlemesini sever misiniz?",
  "Grup seksin bir parçası oldunuz mu hiç?",
  "Ortak cinsel organlarınıza genelde kamu alanında dokunmayı sever misiniz?",
  "Bir oturumda kaç kez boşalabilirsiniz?",
  "Şu anda banyoda öpüşmek için kimseyi seçer misiniz?",
  "Aynı gün farklı insanlarla seks yaptınız mı hiç?",
  "Yüksek sesle inlemeyi sever misiniz?",
  "Seks yaparken kesinlikle öpeceğiniz yer neresidir? (dudaklar haricinde)",
  "Hiç umumi tuvalette mastürbasyon yaptınız mı?",
  "En sevdiğiniz porno yıldızı kimdir?",
  "Çükünüz ne kadar uzun?",
  "Kıçınızın yalanmasını sever misiniz?",
  "Şimdiye kadar kaç farklı seks pozisyonunu denediniz?",
  "Yorucu bir iş gününden sonra başvurduğunuz seks pozisyonu hangisidir?",
  "Zıt cins arkadaşlarınız hakkında hayal kurduğunuz oldu mu hiç?"
  "Vücudunuzun hangi kısmından en emin hissediyorsunuz?",
  "Kesinlikle yapmayı sevdiğiniz bir pozisyon hangisidir?",
  "Sizi tahrik etmek için bir kişinin ne giymesini istersiniz?",
  "Tamamen sarhoşken öpüştünüz mü hiç?",
  "Hiç sınıfta öpüştünüz mü?",
  "Çevrimiçi olarak ünlüleri yarı çıplak görünce hiç azdınız mı?",
  "Son cinsel rüyanızı nasıl tanımlarsınız?",
  "Sizi kesinlikle modunuza sokacak şarkılar nelerdir?",
  "Birini tahrik etmek için en vahşi yer hangisidir?",
  "Senin azdığını belli etmek için mükemmel bir cümle nedir?",
  "Bugüne kadar kullandığımız en iyi prezervatif lezzeti hangisidir?",
  "Başkalarının seks yaparken izlemek sizi tahrik ediyor mu?",
  "Komşuların müdahale etmek zorunda kaldığı kadar yüksek sesle seks yaptınız mı hiç?",
  "Bir çift seks yaparken içeri girdiniz mi hiç?",
  "Aynı cinsiyetle kirli konuşmayı denediniz mi hiç?",
  "Porno aboneliği için ödeme yaptınız mı hiç?",
  "Birbirleriyle arkadaş olan iki kişiyle seks yaptınız mı hiç?",
  "Vücudunuzda şu anda kaç adet dudak izi var?",
  "Hiç biriyle arkadaşlarla faydalar ilişkisi yaşadınız mı?",
  "Hiç bir nude plaja gittiniz mi?",
  "Boyut olarak size iki katı olan biriyle seks yaptınız mı hiç?",
  "Porno izlerken kime dikkat edersiniz?",
  "Tüylerinizi tıraş etmeden yaptınız mı hiç?",
  "Rol yapma için bir kostüm ödünç aldınız mı hiç?",
  "Telefonunuzda en son aradığınız pis şey neydi?",
  "Sen ve en iyi arkadaşınız aynı durumda olsanız, hanginizin daha iyi şansı olduğunu düşünüyorsunuz?",
  "İlişki dışında, çıplak gören başka kimse oldu mu?",
  "Tutanaklarınızı size çekmek için yaptığınız en çılgın şey nedir?",
  "İlk seks rüyanızı kaç yaşında gördünüz?",
  "Bir haftada kaç kez porno izlersiniz?",
  "Toplu halde özel bölgelerinize dokundunuz ve kimse fark etmedi mi?",
  "Anime karakterlerine cinsel olarak çekildiniz mi hiç?",
  "Kaç kez orgazm taklidi yaptınız?",
  "Hiç bir yabancıyla seks yaptınız mı?",
  "Şu an arama geçmişinizde bulabileceğimiz en üst 3 şey nedir?",
  "Listenizdeki bir cinsel pozisyon var mı?",
  "Bir kişinin muz yemesini fark ettiniz mi hiç?",
  "Sahip olduğunuz en üst 3 cinsel sapkınlık nedir?",
  "Seks öncesinde hiç sinirlendiğiniz oldu mu?",
  "Rastgele yabancıları halka açıkta öpüşürken yakaladınız mı hiç?",
  "Sadece azgın olduğunuz için biriyle seks yaptınız mı hiç?",
  "Sizin için yapılmış en iyi seks oyuncağı nedir?",
  "Dişlerinizi fırçalamadan öpüştünüz mü hiç?",
  "Partnerinizin koltukaltını hiç kokladınız mı?",
  "Bir arkadaşınızın eski sevgilisiyle tek gecelik ilişki yaşadınız mı?",
  "Kondom seks öncesinde hiç patladı mı?",
  "Arkadaşlarınızın sizi telefonda inleme sesleriyle yakaladığı oldu mu hiç?",
  "Bir orgazmı nasıl taklit edebilirsiniz?",
  "Yanlışlıkla cinsel bir mesajı yanlış kişiye gönderdiniz mi hiç?",
  "Seks seansının ortasında hiç terk edildiniz mi?",
  "Arkadaşlarınızın sizi kendinizi tatmin ederken yakaladığı oldu mu hiç?",
  "En tuhaf cinsel deneyiminizi hatırlayabiliyor musunuz?",
  "Anime pornografisi izlediniz mi hiç?",
  "Çok tuhaf tatlı bir vücut sıvısı yaladın mı hiç?",
  "Birine sadece üç kez öpüştükten sonra -Seni seviyorum- dediniz mi hiç?",
  "Kamusal bir etkinlikte seks pozisyonunda rol aldın mı hiç?",
  "Hangi ünlü çiftle üçlü yapmak isterdin?",
  "Sprey orgazma şahit oldunuz mu hiç?",
  "Partnerinizle yapmayı düşündüğünüz en pis şey nedir?",
  "Penis hiç vajinanın sonuna dokundu mu?",
  "Sperminizi partnerinizin yüzüne sürdünüz mü hiç?",
  "Partnerinize tükürdünüz mü hiç?",
  "Meme uçlarını emmekten hoşlanır mısınız?",
  "Grup halinde yaptınız mı hiç?",
  "Oraya tıraşsız yapmayı denediniz mi hiç?",
  "Dondurmadan yalamak için en sevdiğiniz vücut bölümü hangisidir?",
  "Seksin sırasında konuşmanın dahil olmasından hoşlanır mısınız?",
  "İkinci rauntlardan hoşlanır mısınız?",
  "Kışkırtma sizi azdırır mı?",
  "Cinsel isteği istekli bir şekilde bastırabilir misiniz?",
  "Seks yaparken romantik olmaktan hoşlanır mısınız?",
  "Yatak odasında partnerinize ne yapmak istediğinizi konuşmaktan hoşlanır mısınız?",
  "Grubun en pis olanı kimdir?",
  "Grubun içinde iş bulmak için seks yapacak olan kim?",
  "Grubun içinde ilk cinsel ilişki yaşayan kimdi?",
  "Okulda en çılgın olan kimdi?",
  "Grubun içinde ilk kez oral seks yapan kim?",
  "Grubun içinde ayrıldıktan sonra eski sevgililerini öpen kim?",
  "Grubun içinde ilk kez tek gecelik ilişki yaşayan kim?",
  "Grubun içinde en olası çıplak yüzme yapacak olan kim?",
  "Grubun içinde bir porno yıldızı olma potansiyeline sahip kim?",
  "Grubun içinde patronuyla seks yapacak olan kim?",
  "Grubun içinde saç fetişi olan kim?",
  "Grubun içinde en büyük sapık kim?",
  "Grubun içinde en fazla penis resmi alan kim?",
  "Grubun içinde hiç kondom kullanmayan kim?",
  "Grubun içinde BDSM yapan kim?",
  "Grubun içinde en seksi vücutları için en çok övgü alan kim?",
  "Grubun içinde fiziksel seks yerine telefon seksini tercih eden kim?",
  "Grubun içinde en sıcak popoya sahip olan kim?",
  "Grubun içinde hiç arabada seks yapmayan kim?",
  "Grubun içinde şu anda en çok azgın olan kim?",
  "Bu gruptan biriyle seks yapmak zorunda kalsaydınız, kiminle yapardınız?",
  "İlk orgazmı aldığınız kişi kimdi?",
  "Bir ilişkideyken başka biriyle seks yaptınız mı hiç?",
  "Partnerinizin cinsel bölgesini tıraş ettiniz mi hiç?",
  "Partnerinizin cinsel bölgesine hangi lakabı verdiniz?",
  "Sekerken hiç gaz kaçırdınız mı?",
  "Komşularınızdan hangisiyle yatmayı seversiniz?",
  "Kamu yerinde öpüşürken izlenmekten rahatsız olur musunuz?",
  "Seks bu kadar uzun sürerse 5 saat boyunca inletebilir misiniz?",
  "Kendi boyutunuz hakkında ne zaman gerçekten utanmıştınız?",
  "En son ne zaman çıplak kaldınız?",
  "Bir prezervatif reklamını görünce azgın olur musunuz?",
  "İlişki içinde olan biriyle seks yaptınız mı hiç?",
  "Aynı cinsiyete ilgi duysaydınız, hangi ünlüyle seks yapardınız?",
  "Yaptığınız en garip rol yapma oyunu nedir?",
  "Ön sevişme hakkında en çok neyi seversiniz?",
  "İlk cinsel deneyiminiz nasıldı? Tam olarak nasıl olduğunu düşündüğünüz gibi mi oldu?",
  "Ebeveynlerinizin seks yaptığını hiç duydunuz mu?",
  "Arkadaşlarınız arasında en güzel popo kime ait?",
  "Bugüne kadar kaç kişiyle öpüştünüz?",
  "Son oral seks yaptığınız kişiyi adlandırın.",
  "Bir bardak içki için bir barmeninizi göğüslerinizi gösterdiniz mi?",
  "Bir müzisyenle tek gecelik ilişkiniz oldu mu hiç?",
  "Oyunun geri kalanında birinin uyluğunuza dokunmasına izin verir misiniz?",
  "Şu anda hangi iç çamaşırını giydiğinizi gösterin.",
  "En muhteşem seks deneyimi yaşadığınız eski sevgiliyi adlandırın.",
  "Flört ettiğiniz en yaşlı kişi kimdi?",
  "Seks yapmaktan zevk almadığınız biri kimdir?",
  "Azgın olduğunuz en utanç verici yer neresiydi?",
  "Şu anda cinsel hayatınızdan tamamen memnun musunuz?",
  "Şu anda kimin çıplak olduğunu görmek istersiniz?",
  "Kamu yerinde yaptığınız en yaramaz şey nedir?",
  "Hangi en yaşlı kişiyle öpüştünüz?",
  "Birisiyle yatmamak için kullandığınız en aptal neden nedir?",
  "Denemediğiniz hangi seks pozisyonu var?",
  "Bir yabancıdan aldığınız en pis mesaj neydi?",
  "Bir striptiz kulübüne gittiniz mi hiç?",
  "Eşcinsel pornosu izlediniz mi hiç?",
  "Aynanın karşısında öpüşmeyi hiç denediniz mi?",
},
truthordare = {
  truth = {
    "En son yılda başınıza gelen en utanç verici şey nedir?",
    "Hiç sıkıntıdan kurtulmak için yalan söylediniz mi ve eğer öyleyse, neydi?",
    "Bir gün için birisiyle hayatınızı değiştirebilseydiniz, kim olurdu ve neden?",
    "Çoğu insanın bilmediği gizli bir yetenek veya beceriniz nedir?",
    "En büyük korkunuz nedir ve sizi neden korkutur?",
    "Geçmişte verdiğiniz bir kararı değiştirme şansınız olsaydı, neyi değiştirirdiniz?",
    "Bu odadaki birine hiç hoşlanma hissettiniz mi? Eğer öyleyse, kimdi?",
    "Hiç gördüğünüz en tuhaf rüya nedir?",
    "Hayatınız boyunca sadece bir tür yiyecek yemek zorunda kalsaydınız, o ne olurdu?",
    "Hiç sınav veya testte kopya çektiniz mi?",
    "Yediğiniz en alışılmadık veya benzersiz şey nedir?",
    "Hiç kurgusal bir karaktere aşık oldunuz mu ve eğer öyleyse, kimdi?",
    "Herhangi bir süper güce sahip olabilseydiniz, o ne olurdu ve nasıl kullanırdınız?",
    "Yaptığınız en cesur şey nedir veya yapmak istediğiniz en cesur şey nedir?",
    "Genellikle gizli tuttuğunuz bir zevkiniz nedir?",
    "Terkedilmiş bir adada mahsur kalsaydınız ve sadece üç şey getirebilseydiniz, bunlar neler olurdu?",
    "Hiç aldığınız en utanç verici takma ad nedir?",
    "En tuhaf veya mantıksız korkunuz nedir?",
    "Bir hafta boyunca birisiyle yaşamak zorunda kalabilseydiniz, kim olurdu ve neden?",
    "Yaptığınız en spontane şey nedir?",
    "Bir bakire misiniz?",
    "Öpüşürken dilinizi kullanmayı sever misiniz?",
    "Partnerinizin vücudundan yalamak için en iyi şey nedir?",
    "Hiç kimseyle kirli doğruluk oyunları oynadınız mı?",
    "Bir oral seks almayı sever misiniz?",
    "En son ne zaman bir el işi yaptınız?",
    "Kamusal yerlerde öpüşmeyi sever misiniz?",
    "Sizi en çok ne tahrik eder?",
    "En sevdiğiniz iç çamaşırı türü nedir?",
    "En son ne zaman öpüştünüz?",
    "Seks yapmak için gittiğiniz ilk yer neresidir?",
    "Dişlerinizle prezervatif yırttınız mı hiç?",
    "Yatak odasında kirli konuşmayı sever misiniz?",
    "En sevdiğiniz öpüşme noktası nedir?",
    "Öpmeye başladığınızda önce nereye dokunursunuz?",
    "Oral seks yapmaktan hoşlanır mısınız?",
    "Hiç kamusal bir yerde porno izlediniz mi?",
    "Kendinize ne sıklıkta dokunursunuz?",
    "Şu anda azgın hissediyor musunuz?",
    "En son bir oral seks aldığınız zaman neydi?",
    "24 saat içinde kaç kez seks yaptınız?",
    "Bir cinsel sohbet sırasında kullandığınız en iyi emojiler hangileri?",
    "Buraya gelmeden önce hiç çıplak selfie göndereniniz oldu mu?",
    "Asansör yolculuğu nasıldı? (yumuşak bir espri yapıp kartlarınızı oynayın)",
    "En vahşi cinsel arzunuz nedir?",
    "Yatak odasında keşifçi tip misiniz?",
    "Bir tamamen yabancıdan bir oral seks aldınız mı hiç?",
    "Bu gruptan biriyle arkadaşlarla faydalar ilişkisi yaşar mısınız?",
    "Arabanızda yaptığınız en zorlu seks pozisyonu nedir?",
    "Açık ilişkilerde bulundunuz mu hiç?",
    "Bir seferde ağzınızda kaç kez boşalabilirsiniz?",
    "İnsanların sizi seks yaparken izlemesini sever misiniz?",
    "Grup seksin bir parçası oldunuz mu hiç?",
    "Partnerinizin genital bölgesine halka açık bir yerde dokunmayı sever misiniz?",
    "Bir oturumda kaç kez boşalabilirsiniz?",
    "Şu anda kiminle banyoda öpüşmeyi tercih edersiniz?",
    "Hala iç çamaşırı giyerken seks yapmak daha çılgınca mı?",
    "Kimin ağzından alkol içmek istersiniz?",
    "Sert bir seans denemeyi hiç düşündünüz mü?",
    "Aynı gün farklı insanlarla seks yaptınız mı hiç?",
    "Fransız öpücüğünü sever misiniz?",
    "Öpüşürken nazik olmayı mı tercih edersiniz?",
    "Bekaretinizi kaybettiğiniz yaş kaçtı?",
    "Öpülmek için en sevdiğiniz bölüm nedir?",
    "Mastürbasyon yapmak istediğinizde hangi porno izlersiniz?",
    "Kolej kafeteryasında öpüştünüz mü hiç?",
    "Yüksek sesle inlemeyi sever misiniz?",
    "Öpüşürken kucağınızda oturmayı sever misiniz?",
    "Azgınsanız dudaklarınıza ısırır mısınız?",
    "Hangi ünlüyle tek gecelik ilişki yaşamaktan hoşlanırsınız?",
    "Yalnızken meme uçlarınızı ovuşturdunuz mu hiç?",
    "Kendi çıplak fotoğraflarınızı görmek için fotoğraf çektiniz mi hiç?",
    "İlk kez mastürbasyon yaparken içine kaç parmak denediniz?",
    "Erotik romanlar okudunuz mu hiç?",
    "Boyut sizin için önemli mi?",
    "Birini baştan çıkarmak için serseri elbise giydiniz mi hiç?",
    "Erkek kardeş/kuzeninizin arkadaşlarına yürüdünüz mü hiç?",
    "Bir erkeğin pantolonundan penisi kontrol etmeye çalıştınız mı hiç?",
    "Sinema salonunda seks yaptınız mı hiç?",
    "Eğer isteseydim, sevişme teklifime hazır olur musunuz?",
    "Bir oral seks yapmak için en sevdiğiniz pozisyon hangisi?",
    "Tek elle sütyeninizi çözmeme izin ister misiniz?",
    "Eğer isteseydim, iç çamaşırı giymeden dışarı çıkar mısınız?",
    "Vücudunuzun her yerine öptüğümde gözlerinizi kapatmak ister misiniz?",
    "Meme altlarınızın altında size çok fazla ısırık yapmamı ister misiniz?",
    "Sizi duvara itip öpüşmemi ister misiniz?",
    "Bir ağıza oral seks yapmayı seviyor musunuz?",
    "İçeri 3 parmak alabilir misiniz?",
    "Eğer isteseydim, yumurtalarımı yalayabilir misiniz?",
    "Öpüşürken dudaklarımı ısırır mısınız?",
    "Sizi boğazlar mı seversiniz?",
    "Saçlarınızı geri çekmemi ister misiniz?",
    "Üzerinize gittiğimde sert olmayı sever misiniz?",
    "Külotumu koklayabilir miyim?",
    "Oraya biraz alkol sürüp yalayabilir miyim?",
    "Seks yaparken kesinlikle öpeceğiniz yer neresi? (dudaklar hariç)",
    "Halka açık bir tuvalette mastürbasyon yaptınız mı hiç?",
    "Favori porno yıldızınız kim?",
    "Eğer istekliyseniz yatağa ne giyersiniz?",
    "Bir kadının hangi bölgesini önce fark edersiniz?",
    "Gizlice birinin özel bölgelerine dokunup hoşunuza giden oldu mu hiç?",
    "Bikinili bir kıza hiç bakınız mı?",
    "Öpüşürken tamamen içine gitmeyi sever misiniz?",
    "Hangi renk iç çamaşırını görmek istersiniz?",
    "İlk kez çıplak bir kadın gördüğünüz yer neresiydi?",
    "Bir parkta bir el işi aldınız mı hiç?",
    "Benimle ilgili en vahşi düşünceniz nedir?",
    "Öpüşürken partnerinizi önden mi yoksa arkadan mı tutmayı sever misiniz?",
    "Partnerinizin vücudunda öpüşmeye başladığınızda elleriniz ilk nereye gider?",
    "Bir otel odasında sert bir öpüşme seansı yaşadınız mı hiç?",
    "Asansörde öpüştünüz mü hiç?",
    "Penisiniz ne kadar uzun?",
    "Poponuzun yalanmasını sever misiniz?",
    "Şimdiye kadar kaç farklı seks pozisyonunu denediniz?",
    "Yorucu bir iş gününden sonra tercih ettiğiniz seks pozisyonu hangisi?",
    "En son kendiniz olmadığınızı hissettiğiniz zaman ne zaman oldu?",
    "Yoga için en sevdiğiniz pozisyon hangisi?",
    "En son deli bir tek gecelik ilişki yaşadığınız ve bu delice olduğu için ne zaman oldu?",
    "Seksle ilgili en sevdiğiniz anınız nedir?",
    "Hayatınızda en elektrik veren dokunuşunuz hangisiydi ve neden?",
    "Partnerinizle birlikte yaptığınız en tuhaf şey nedir?",
    "Hiç başka kimseye olamayacak bir gece olayınız var mı?",
    "Hiç kimseyi alt edemeyeceğinize inandığınız bir cinsel anınız var mı?",
  },
  dare = {
    "Bir sonraki iki dakika boyunca hiç kimse izlemiyormuş gibi dans et.",
    "İletişim listendeki üçüncü kişiye muz emojisi gönder ve cevabını oku.",
    "Üç tur boyunca istediğin bir aksanla konuş.",
    "Yanına gidip -Ben bir süper kahramanım!- diye bağır.",
    "Sosyal medya hesabında komik bir durum veya resim paylaş.",
    "Grubun seçtiği bir şarkıyı en yüksek sesle söyle.",
    "İki dakika boyunca en iyi hayvan taklitini yap.",
    "Beğendiğin kişiyi (veya uzun zamandır konuşmadığın birini) ara ve rastgele bir şey söyle.",
    "Benim seçtiğim bir şarkıya striptiz dansı yap.",
    "En seksi alıntılarını kullanarak beni baştan çıkar.",
    "Ünlü bir çizgi film karakterinin en iyi taklidini yap.",
    "Zor bir dil bükme türküsü söylerken 10 jumping jack yap.",
    "Eski sevgiline çılgın bir iltifat gönder.",
    "Odadaki rastgele bir nesneyi bul ve onu satmak için kısa bir reklam yap.",
    "Mevcut işine nasıl başladığına dair komik ve kurgusal bir hikaye yarat.",
    "Bir arkadaşını ara ve ona doğum gününü kutla, hatta doğum günü değilse bile.",
    "Grup için kısa bir stand-up komedi rutini yap.",
    "Ünlü bir film karakterinin en iyi taklidini yap.",
    "Geçmişinden komik veya utanç verici bir anı paylaş.",
    "İletişim listendeki beşinci kişiye bir iltifat gönder.",
    "Son yediğin şey hakkında kısa bir rap yap.",
    "Birini seç ve ona flört et.",
    "İletişim listendeki ilk kişiye komik bir meme veya GIF gönder.",
    "Birine eğilerek serenat yap.",
    "Doğuyormuş gibi bebek sesi yap.",
    "Sağındaki kişinin senden ayrılmaması için yalvar.",
    "Sola kalan kişiye sırtında taşı.",
    "Telefonundaki son 5 mesajı oku.",
    "Eski sevgilinin son mesajını oku.",
    "Koltukla 5 dakika boyunca tartış.",
    "Birini ara ve 5 kuruş borç iste.",
    "En iyi arkadaşını ara ve ona nişanlandığını söyle.",
    "Kulağıma bir sır fısılda.",
    "Beni tanımıyormuş gibi bana yaklaş.",
    "Beni dokunmadan heyecanlandırmaya çalış.",
    "Bana bir kucağa oturma dansı yap.",
    "Beni 10 kez şaplakla.",
    "Gömleğini çıkar.",
    "Pantolonunu çıkar.",
    "Ayakkabılarını çıkar.",
    "Birine FaceTime yap ve ona âşık olduğunu söyle.",
  }
}

 --Turkish translated by nt aka nicetrydev for cDev
 
